=== Ertibus/saityno-pd3/planets.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- XSD validation file for: planets.xml -->
    <!-- Root element -->
    <xs:element name="planets" type="planetsType"/>
    <!-- Orbit time object - Time it takes for the planet to orbit around the sun  -->
    <xs:complexType name="orbit-timeType">
        <!-- Atributes of orbit-time object-->
        <xs:sequence>
            <!-- Orbit time in years -->
            <xs:element type="xs:float" name="years"/>
            <!-- Orbit time in days -->
            <xs:element type="xs:float" name="days"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Surface area object -->
    <xs:complexType name="surface-areaType">
        <xs:sequence>
            <!-- Surface area in km^2 -->
            <xs:element type="xs:long" name="km2"/>
            <!-- Surface area in proportion to Earth -->
            <xs:element type="xs:float" name="earths"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Temeprature object -->
    <xs:complexType name="temperatureType">
        <!-- Atributes of temeprature object-->
        <xs:sequence>
            <!-- Min temperature of the planets surface in Kelvin (K) -->
            <xs:element name="min" type="xs:string"/>
            <!-- Mean temperature of the planets surface in Kelvin (K) -->
            <xs:element name="mean" type="xs:string"/>
            <!-- Max temperature of the planets surface in Kelvin (K) -->
            <xs:element name="max" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Planet object -->
    <xs:complexType name="planetType">
        <!-- Attributes of planet object -->
        <xs:sequence>
            <!-- Planets id -->
            <xs:element name="id" type="xs:int"/>
            <!-- Planets name -->
            <xs:element name="name" type="xs:string"/>
            <!-- God the planet is named after -->
            <xs:element name="god" type="xs:string"/>
            <!-- God aspect -->
            <xs:element name="god-aspect" type="xs:string"/>
            <!-- Orbit time object -->
            <xs:element name="orbit-time" type="orbit-timeType"/>
            <!-- How fast is the planet orbiting around the sun (km/s) -->
            <xs:element name="orbital-speed" type="xs:float"/>
            <!-- The minimum speed needed to escape from the gravitational influence of the sun. (km/s) -->
            <xs:element name="escape-velocity" type="xs:float"/>
            <!-- Surface gravity (m/s^2) -->
            <xs:element name="gravity" type="xs:float"/>
            <!-- Surface pressure (kPa); "type=string" because no pressure data on some of the planets -->
            <xs:element name="surface-pressure" type="xs:string"/>
            <!-- Surface area object -->
            <xs:element name="surface-area" type="surface-areaType"/>
            <!-- Number of NATURAL satellites -->
            <xs:element name="satellites" type="xs:int"/>
            <!-- Temperature Object -->
            <xs:element name="temperature" type="temperatureType"/>
        </xs:sequence>
    </xs:complexType>
    <!-- List planets of planet object -->
    <xs:complexType name="planetsType">
        <xs:sequence>
            <xs:element name="planet" type="planetType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ertibus/saityno-pd3/planets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- PD 1 -->
<!-- Topic: Planets -->
<!-- Validation: XSD -->
<planets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\planets.xsd">
    <planet>
        <name>Mercury</name>
        <god>Hermes</god>
        <god-aspect>Commerce</god-aspect>
        <orbit-time>
            <years>0.240846</years>
            <days>87.97</days>
        </orbit-time>
        <orbital-speed>47.362</orbital-speed>
        <escape-velocity>11.186</escape-velocity>
        <gravity>3.7</gravity>
        <surface-pressure>0.0001</surface-pressure>
        <surface-area>
            <km2>74800000</km2>
            <earths>0.147</earths>
        </surface-area>
        <satellites>0</satellites>
        <temperature>
            <min>90</min>
            <mean>270</mean>
            <max>540</max>
        </temperature>
    </planet>
    <planet>
        <name>Venus</name>
        <god>Venus</god>
        <god-aspect>Love and Beauty</god-aspect>
        <orbit-time>
            <years>0.615198</years>
            <days>224.701</days>
        </orbit-time>
        <orbital-speed>35.02</orbital-speed>
        <escape-velocity>10.36</escape-velocity>
        <gravity>8.87</gravity>
        <surface-pressure>9200</surface-pressure>
        <surface-area>
            <km2>460230000</km2>
            <earths>0.902</earths>
        </surface-area>
        <satellites>0</satellites>
        <temperature>
            <min/>
            <mean>737</mean>
            <max/>
        </temperature>
    </planet>
    <planet>
        <name>Earth</name>
        <god/>
        <god-aspect/>
        <orbit-time>
            <years>1</years>
            <days>365.256363004</days>
        </orbit-time>
        <orbital-speed>29.78</orbital-speed>
        <escape-velocity>11.186</escape-velocity>
        <gravity>9.8</gravity>
        <surface-pressure>101.325</surface-pressure>
        <surface-area>
            <km2>510072000</km2>
            <earths>1</earths>
        </surface-area>
        <satellites>1</satellites>
        <temperature>
            <min>184</min>
            <mean>287.16</mean>
            <max>330</max>
        </temperature>
    </planet>
    <planet>
        <name>Mars</name>
        <god>Mars</god>
        <god-aspect>War</god-aspect>
        <orbit-time>
            <years>1.88082</years>
            <days>686.971</days>
        </orbit-time>
        <orbital-speed>24.007</orbital-speed>
        <escape-velocity>5.027</escape-velocity>
        <gravity>3.72076</gravity>
        <surface-pressure>0.636</surface-pressure>
        <surface-area>
            <km2>144798500</km2>
            <earths>0.284</earths>
        </surface-area>
        <satellites>2</satellites>
        <temperature>
            <min>130</min>
            <mean>210</mean>
            <max>308</max>
        </temperature>
    </planet>
    <planet>
        <name>Jupiter</name>
        <god>Jupiter</god>
        <god-aspect>Sky and Thunder</god-aspect>
        <orbit-time>
            <years>11.862</years>
            <days>4332.59</days>
        </orbit-time>
        <orbital-speed>13.07</orbital-speed>
        <escape-velocity>59.5</escape-velocity>
        <gravity>27.79</gravity>
        <surface-pressure>400</surface-pressure>
        <surface-area>
            <km2>61419000000</km2>
            <earths>120.4</earths>
        </surface-area>
        <satellites>79</satellites>
        <temperature>
            <min>130</min>
            <mean>210</mean>
            <max>308</max>
        </temperature>
    </planet>
    <planet>
        <name>Saturn</name>
        <god>Saturn</god>
        <god-aspect>Wealth and Agriculture</god-aspect>
        <orbit-time>
            <years>29.4571</years>
            <days>10759.22</days>
        </orbit-time>
        <orbital-speed>9.68</orbital-speed>
        <escape-velocity>35.5</escape-velocity>
        <gravity>10.44</gravity>
        <surface-pressure>140</surface-pressure>
        <surface-area>
            <km2>42700000000</km2>
            <earths>83.703</earths>
        </surface-area>
        <satellites>82</satellites>
        <temperature>
            <min/>
            <mean>109</mean>
            <max/>
        </temperature>
    </planet>
    <planet>
        <name>Uranus</name>
        <god>Uranus</god>
        <god-aspect>Sky</god-aspect>
        <orbit-time>
            <years>84.0205</years>
            <days>30688.5</days>
        </orbit-time>
        <orbital-speed>6.8</orbital-speed>
        <escape-velocity>21.3</escape-velocity>
        <gravity>8.69</gravity>
        <surface-pressure/>
        <surface-area>
            <km2>8115600000</km2>
            <earths>15.91</earths>
        </surface-area>
        <satellites>27</satellites>
        <temperature>
            <min>47</min>
            <mean>53</mean>
            <max>57</max>
        </temperature>
    </planet>
    <planet>
        <name>Neptune</name>
        <god>Neptune</god>
        <god-aspect>Sea</god-aspect>
        <orbit-time>
            <years>164.8</years>
            <days>60182</days>
        </orbit-time>
        <orbital-speed>5.43</orbital-speed>
        <escape-velocity>23.5</escape-velocity>
        <gravity>11.15</gravity>
        <surface-pressure/>
        <surface-area>
            <km2>7618300000</km2>
            <earths>14.98</earths>
        </surface-area>
        <satellites>14</satellites>
        <temperature>
            <min/>
            <mean>72</mean>
            <max/>
        </temperature>
    </planet>
    <planet>
        <name>Pluto</name>
        <god>Pluto</god>
        <god-aspect>Underworld</god-aspect>
        <orbit-time>
            <years>247.94</years>
            <days>90560</days>
        </orbit-time>
        <orbital-speed>4.743</orbital-speed>
        <escape-velocity>1.212</escape-velocity>
        <gravity>0.620</gravity>
        <surface-pressure>0.001</surface-pressure>
        <surface-area>
            <km2>17790000</km2>
            <earths>0.035</earths>
        </surface-area>
        <satellites>5</satellites>
        <temperature>
            <min>33</min>
            <mean>44</mean>
            <max>55</max>
        </temperature>
    </planet>
    <planet>
        <name>Eris</name>
        <god>Eris</god>
        <god-aspect>Strife and Discord</god-aspect>
        <orbit-time>
            <years>559.07</years>
            <days>204199</days>
        </orbit-time>
        <orbital-speed>3.434</orbital-speed>
        <escape-velocity>1.38</escape-velocity>
        <gravity>0.82</gravity>
        <surface-pressure/>
        <surface-area>
            <km2>17000000</km2>
            <earths>0.033</earths>
        </surface-area>
        <satellites>1</satellites>
        <temperature>
            <min>30</min>
            <mean>42.5</mean>
            <max>55</max>
        </temperature>
    </planet>
</planets>
